### ISSUE TITLE
Buffer Underrun, Broken Pipe, Service Restart when Pausing Raspotify

### ISSUE THREAD

**Issue by y8s** [HEnquist/camilladsp#131] opened 2021-08-19 15:41 UTC
I could use a little help finessing my installation and setup. More detail here:
https://github.com/HEnquist/camillagui-backend/issues/35

Short version:
Pi Zero W
USB OTG hub
3x USB Audio adapters (Realtek 5686)
running Raspbian Buster 5.10.17+ kernel
raspotify + CamillaDSP + CamillaGUI-Backend

So recently I added a third USB dongle. They are now all the same type using Realtek DACs. They all are configured and working mostly as expected (I can map filters to each channel and observe the result) but I'm having some strange issues. 

I can load up Spotify (using raspotify) and play to Camilla. Sometimes it stutters at start. But whenI pause spotify, Camilla throws a bunch of buffer underruns and eventually a broken pipe (snd_pcm_readi) which crashes Camilla. My systemd service file restarts it but it happens like clockwork. It DOES tend to recover after a restart but it takes a little while. See below:

<details>
<summary>Expand me: Captured syslog from the moment I hit "pause":</summary>

```
Aug 19 11:20:43 streamy camilladsp[4090]: Aug 19 11:20:42.202 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:43 streamy camilladsp[4090]: Aug 19 11:20:42.289 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:43 streamy camilladsp[4090]: Aug 19 11:20:42.399 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.485 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.547 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.608 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.608 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.670 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.732 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.794 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.794 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.857 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.918 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.980 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:42.980 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.042 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.104 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.165 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.165 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.228 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.289 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.350 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.350 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.412 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.475 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:44 streamy camilladsp[4090]: Aug 19 11:20:43.535 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.536 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.598 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.660 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.722 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.722 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.784 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.887 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.949 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:43.950 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.012 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.073 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.140 WARN Prepare capture device, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.140 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.212 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.281 WARN Capture failed, error: ALSA function 'snd_pcm_readi' failed with error 'EPIPE: Broken pipe', module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.282 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.305 ERRO Capture error: ALSA function 'snd_pcm_readi' failed with error 'EPIPE: Broken pipe', module: camilladsp
Aug 19 11:20:45 streamy systemd[1]: camilladsp.service: Succeeded.
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.353 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.422 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.492 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.561 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.619 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.676 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.734 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:45 streamy camilladsp[4090]: Aug 19 11:20:44.792 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 19 11:20:49 streamy systemd[1]: camilladsp.service: Service RestartSec=5s expired, scheduling restart.
Aug 19 11:20:49 streamy systemd[1]: camilladsp.service: Scheduled restart job, restart counter is at 11.
Aug 19 11:20:50 streamy systemd[1]: Stopped CamillaDSP Daemon.
Aug 19 11:20:50 streamy systemd[1]: Started CamillaDSP Daemon.
Aug 19 11:20:50 streamy camilladsp[4099]: Aug 19 11:20:50.537 INFO Capture device supports rate adjust, module: camillalib::alsadevice
Aug 19 11:20:50 streamy camilladsp[4099]: Aug 19 11:20:50.570 INFO Starting playback from Prepared state, module: camillalib::alsadevice
Aug 19 11:20:51 streamy camilladsp[4099]: Aug 19 11:20:51.000 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice

```

</details>

I have played around with adjusting samplerate, chunksize, queuelimit, enable_rate_adjust and maybe others. None seem to really affect anything (though raspotify refuses to work at any sample rate besides 44100...)

Thanks for your help.

**Comment by HEnquist** [comment] 2021-08-19 19:04
Are you still using an alsa loopback, like here? https://gist.github.com/y8s/c032f3a2ba12504eff5f0184f0dec7d1

If yes, there is something very odd going on. The loopback i supposed to completely isolate what happens on the playback and capture sides. CamillaDSP should not be affected in any way by what raspotify is doing. The only thing that should happen when you pause, is that camilladsp should only capture silence. But it should still get samples, at the same rate as when music was playing. I have never seen it do anything else.

**Comment by y8s** [comment] 2021-08-19 19:54
Here's my current config. Similar to the link above.
https://gist.github.com/y8s/9479529500b4fa262930d7261877ef00 

So the buffer is still being filled with silence when it's paused? 

I tried also from the command line:
aplay testfile.wav
and when the file ends, camilla throws a bunch of underruns or the broken pipe in snd_pcm_readi or crashes and quits.

**Comment by HEnquist** [comment] 2021-08-20 07:12
Just tried the same, with aplay and the loopback. Camilladsp keeps receiving samples no matter what aplay is doing. This is on Fedora 34, kernel 5.13.9.

What happens if you do the the aplay test again, but try capturing from the loopback with arecord instead of camilladsp?

If the loopback refuses to work normally, you could try enabling the "retry_on_error" setting in camilladsp. Could work.

**Comment by y8s** [comment] 2021-08-20 15:24
I tried with `arecord -D hw:Loopback -f cd | aplay` and `arecord -D hw:Loopback,1,1 -f cd | aplay`
and I still get underruns and the occasional broken pipe. I'm not sure if that's the right method for what you suggest. The above just plays silence to camillaDSP.

I might be misunderstanding what your intention is.

`retry_on_error: false` didn't do much.

**Comment by HEnquist** [comment] 2021-08-20 19:25
I was thinking of using two terminals, in one you run arecord:
```
arecord -D hw:Loopback,0,0 -r 44100 -f S16_LE > dump.wav
```
First run it for a few seconds to check that the dump.wav file seems to be growing at about 170 kB/second. It shoud do that even if no app is playing any music.
Then start it again, and while it runs, also start aplay in the second terminal:
```
aplay testfile.wav
```
Let that run for a bit also to and check that the size of dump.wav makes sense. I assumed your testfile.wav is 2 channels at 44.1kHz, 16 bits. Adjust the arecord command as needed.

**Comment by HEnquist** [comment] 2021-08-20 19:28
> 
> `retry_on_error: false` didn't do much.

Try setting it to true!

**Comment by y8s** [comment] 2021-08-20 19:32
> > `retry_on_error: false` didn't do much.
> 
> Try setting it to true!

Oops, I copy-pasted after returning it to default. I tried true and that's what did't change anything. Above test coming shortly.

**Comment by y8s** [comment] 2021-08-20 19:42
> I was thinking of using two terminals, in one you run arecord:
> 
> ```
> arecord -D hw:Loopback,0,0 -r 44100 -f S16_LE > dump.wav
> ```
> 
> First run it for a few seconds to check that the dump.wav file seems to be growing at about 170 kB/second. It shoud do that even if no app is playing any music.
> Then start it again, and while it runs, also start aplay in the second terminal:
> 
> ```
> aplay testfile.wav
> ```
> 
> Let that run for a bit also to and check that the size of dump.wav makes sense. I assumed your testfile.wav is 2 channels at 44.1kHz, 16 bits. Adjust the arecord command as needed.

Window 1 (the overruns were after a bit):
```
pi@streamy:~ $ arecord -D hw:Loopback,0,0 -r 44100 -f S16_LE > dump.wav
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
overrun!!! (at least 1272.179 ms long)
overrun!!! (at least 347.707 ms long)
overrun!!! (at least 379.217 ms long)
overrun!!! (at least 873.564 ms long)
overrun!!! (at least 1077.945 ms long)
overrun!!! (at least 210.944 ms long)
overrun!!! (at least 327.233 ms long)
^CAborted by signal Interrupt...

```

Window 2:
```
pi@streamy:~ $ aplay test.wav
Playing WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

```

Window 3:
```
pi@streamy:~ $ tail -f /var/log/syslog
Aug 20 15:39:00 streamy camilladsp[4137]: Aug 20 15:39:00.386 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:00 streamy camilladsp[4137]: Aug 20 15:39:00.455 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:00 streamy camilladsp[4137]: Aug 20 15:39:00.566 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:00 streamy camilladsp[4137]: Aug 20 15:39:00.675 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:00 streamy camilladsp[4137]: Aug 20 15:39:00.675 WARN Capture failed, error: ALSA function 'snd_pcm_readi' failed with error 'EPIPE: Broken pipe', module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.699 ERRO Capture error: ALSA function 'snd_pcm_readi' failed with error 'EPIPE: Broken pipe', module: camilladsp
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.737 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.797 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.847 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.895 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.944 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy camilladsp[4137]: Aug 20 15:39:00.993 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 20 15:39:01 streamy systemd[1]: camilladsp.service: Succeeded.
Aug 20 15:39:06 streamy systemd[1]: camilladsp.service: Service RestartSec=5s expired, scheduling restart.
Aug 20 15:39:06 streamy systemd[1]: camilladsp.service: Scheduled restart job, restart counter is at 5.
Aug 20 15:39:06 streamy systemd[1]: Stopped CamillaDSP Daemon.
Aug 20 15:39:06 streamy systemd[1]: Started CamillaDSP Daemon.
Aug 20 15:39:06 streamy camilladsp[4147]: Aug 20 15:39:06.775 INFO Capture device supports rate adjust, module: camillalib::alsadevice
Aug 20 15:39:06 streamy camilladsp[4147]: Aug 20 15:39:06.807 INFO Starting playback from Prepared state, module: camillalib::alsadevice
Aug 20 15:39:07 streamy camilladsp[4147]: Aug 20 15:39:07.237 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice

```

**Comment by HEnquist** [comment] 2021-08-21 21:17
I have been trying to reproduce your troubles.
First test, latest 64-bit Raspberry Pi OS with kernel 5.14 release candidate.
Second, a standard 32-bit Raspberry Pi OS (freshly updated) with kernel 5.10.52-v7l+.

The result is that everything works just fine on both. I can freely start and stop playback with aplay to the Loopback, without affecting what happens on the capture side. CamillaDSP just continues receiving samples at the correct rate no matter what I do with aplay.

Unfortunately this means I don't have any idea of what's wrong in your setup.

**Comment by y8s** [comment] 2021-08-22 03:42
I think my next course is to reinstall everything. I have the configuration pretty well sorted so restarting should be easy enough.

Any advice on kernels or is the standard pi buster good enough?

Thank you for all the help with this.

**Comment by HEnquist** [comment] 2021-08-22 09:33
A fresh start would be a good thing to try yes. I would then use another sd card, to keep the existing installation intact until the new one is ready.

I think the standard kernel is fine. If you get problems with random underruns, then first try increasing the priority of the camilladsp process. If it doesn't help, then perhaps a realtime kernel could be worth a try.

**Comment by y8s** [comment] 2021-08-23 16:16
Reinstalled and slightly different results:
when running from command line: `camilladsp -p 1234 active_config.yml` 
it does not crash when playback stops (aplay local file or raspotify), but it does throw lots of underruns and sample rate change warnings. for example:
```

Aug 23 12:08:06.135 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:06.415 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:06.607 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:06.895 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:06.957 WARN sample rate change detected, last rate was 4266.6930372000215 Hz, module: camillalib::alsadevice
Aug 23 12:08:07.093 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:07.385 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:07.565 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:07.873 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:08.070 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:08.355 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:08.417 WARN sample rate change detected, last rate was 4208.000468698927 Hz, module: camillalib::alsadevice
Aug 23 12:08:08.557 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:08.845 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:09.028 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:09.325 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:09.505 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:09.795 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:09.857 WARN sample rate change detected, last rate was 4266.885620124394 Hz, module: camillalib::alsadevice
Aug 23 12:08:09.991 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:10.283 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:10.477 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:10.765 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:10.944 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:11.236 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:11.297 WARN sample rate change detected, last rate was 4265.431157872845 Hz, module: camillalib::alsadevice
Aug 23 12:08:11.430 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:11.725 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:11.910 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:12.196 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:12.375 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:12.675 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:12.727 WARN sample rate change detected, last rate was 4297.013654191008 Hz, module: camillalib::alsadevice
Aug 23 12:08:12.870 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:13.155 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:13.351 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:13.592 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:13.820 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 12:08:14.075 WARN Prepare capture device, module: camillalib::alsadevice
Aug 23 12:08:14.145 WARN sample rate change detected, last rate was 4346.12098367437 Hz, module: camillalib::alsadevice

```

When using the systemd service file, it DOES crash after playback stops. 

[asound.conf.txt](https://github.com/HEnquist/camilladsp/files/7033401/asound.conf.txt)
[active_config.yml.txt](https://github.com/HEnquist/camilladsp/files/7033408/active_config.yml.txt)

**Comment by y8s** [comment] 2021-08-23 18:01
Playing around a bit more... as soon as I add the configuration for pulseaudio linked here
https://github.com/HEnquist/camilladsp-config#pulseaudio

I start getting the broken pipes again.

In fact, once I undo those changes and restart pulse (or reboot), the broken pipes continue happening.

again, UNLESS I run camilla directly from the command line.

Question: Are the warnings above (in the previous post) a problem?

**Comment by HEnquist** [comment] 2021-08-23 18:42
Each warnings in the log probably means there was an interruption. Fine if it's not playing anything, but maybe not that great when trying to listen to music :)
Could you try having "top" running in another terminal while running like you did to catch that log? I wonder if you simply run out of CPU cycles. Things aren't making a lot of sense, but the Pi Zero is much weaker than the devices I have done nearly all testing on.
Any particular reason you use the Zero, or could you use a Pi 2 or faster instead? Do you have one you could try?

**Comment by y8s** [comment] 2021-08-23 19:05
The warnings are only after pausing. I only get maybe two of these after pressing play on raspotify or a wav with aplay.
```
Aug 23 14:46:12.056 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
Aug 23 14:46:12.574 WARN Prepare playback after buffer underrun, module: camillalib::alsadevice

```
The rest happen after pausing/stopping. And restarting prevents them from scrolling nearly as long--so I think that's good progress.

I notice that this all occurs between pressing pause on raspotify or cancelling playback of a wav and camilla responding to detected silence (-60, 3 seconds) and pausing itself. Once it changes to State: Paused, the scrolling stops.

htop shows this (in summary):
1. gui running, camilladsp idle/paused: GUI @8-10% CPU & camilladsp @ 11-12% CPU
2. spotify playing: GUI @ 8-10% CPU & camilladsp @ 25-21% CPU, Total CPU usage: 65-70% (a few underruns)
3. paused: GUI @ 6-8% CPU, camilladsp @ 78-82% CPU (CPU maxed out) until camilla pauses

I notice that during #2, I get the occasional broken pipe from snd_pcm_writei and eventually it'll cause camilla to crash. I've noticed that even scrolling the camilla log window where camilladsp is running can result in a broken pipe. So I tried running apt updates in another window and it crashed almost immediately.

I think you're right about the pi zero just not being powerful enough which is too bad--it's so cheap!

I have an original Pi Model B, a 3 B+, and a couple of Pi 400s. While I'm pretty certain the 3 and 400 will work, they're not exactly budget compared to the zero. Still, I will give one of them a shot just to see how it works. I  have a 3B+ running just pihole and that could really move to another piece of hardware.

Last question: does neon support matter that much? The zero doesn't support it.

**Comment by HEnquist** [comment] 2021-08-23 19:34
> I notice that this all occurs between pressing pause on raspotify or cancelling playback of a wav and camilla responding to detected silence (-60, 3 seconds) and pausing itself. Once it changes to State: Paused, the scrolling stops.
> 

Ah then I finally have a theory! It could be denormal numbers: https://en.wikipedia.org/wiki/Denormal_number
Those are floating point numbers where the value is very very small, which would happen when feeding silence to a BiQuad for a little while. Most FPUs need a bit more more time to do calculations with denormals, and some much more (it can be more than a factor 10). The Pi Zero has a pretty basic FPU which is likely to suffer from this.

> Last question: does neon support matter that much? The zero doesn't support it.

The important thing is simply that the Pi 2 and above have far more powerful CPUs (and FPUs) than the 0 and 1, as well as 4 cores vs 1. In CamillaDSP it's only the asynchronous resampler that is optimized for Neon (and then only when using a 64-bit OS). But the compiler seems to often use Neon instructions instead of the FPU for normal floating point operations, so they are likely faster.

**Comment by y8s** [comment] 2021-08-24 15:23
Pi 3 B+ has none of the underrun / broken pipe / crashing issues so far with the same configuration. 


...



One thing I did notice is that while raspotify does automatically figure out the correct  default playback device, aplay does not.  Does this have to do with `pcm.!default` and `ctl.!default` being set to different cards in the asound.conf in your camilla-config repo? I've goofed around with the config but aplay never seems to work without an explicit device.

for example: raspotify just works, but for aplay I have to use `aplay testfile.wav -Dcamilldsp` for it to work.

**Comment by HEnquist** [comment] 2021-08-24 19:36
Great! The pi 3 seems to generally work very well.

I don't really know about the default Alsa devices. It's included in my example because it was there in the example I started from, but I always specify the device instead of relying on the default.

**Comment by HEnquist** [comment] 2021-08-30 21:40
I'm closing this issue, please reopen or make a new one if more problems show up.

**Closed by HEnquist** 2021-08-30 21:40 UTC
