### ISSUE TITLE
Convolution

### ISSUE THREAD

**Issue by ElliottBridge** [HEnquist/camilladsp#198] opened 2022-05-06 13:51 UTC
Hi, when looking at the filter graphs for convolution, all of the filters show up being shifted to the right in frequency.
E.g. 500hz crossover point showing as 600hz. 20hz boost showing as 30hz boost. Is there something wrong with the implementation, or just the camilladsp graphing?

**Comment by ElliottBridge** [comment] 2022-05-06 13:53
![image](https://user-images.githubusercontent.com/51234228/167146596-f81be2d7-a1cc-4cb9-9fd1-79acaabb24a1.png)
![image](https://user-images.githubusercontent.com/51234228/167146665-54413292-3957-4c3f-b494-c0d328e86503.png)
See what I mean? Also, it should be linear phase as seen in the program, but camilladsp is showing lots of phase change

**Comment by ElliottBridge** [comment] 2022-05-06 13:55
The program used to generate the files is not the problem. It's called rePhase and is highly effective at what it does. The files show up correctly when using Equaliser APO as well, which just confirms my suspicions.

**Comment by HEnquist** [comment] 2022-05-06 16:44
This is most likely caused by some error in the plotting part of the GUI. I'm guessing it's something with the x-scale display rather than the data. I'm working on this part right now, will check this too!

**Comment by ElliottBridge** [comment] 2022-05-06 22:30
> This is most likely caused by some error in the plotting part of the GUI. I'm guessing it's something with the x-scale display rather than the data. I'm working on this part right now, will check this too!

Thank you so much! Good to know it's processing correctly at least! Some time down the line I'll be featuring this program on my YouTube channel as a more powerful and far cheaper alternative to the miniDSP, instead just a bit more involved in setting up a raspberry pi. I'll be sure to link your donation page from GitHub!

**Comment by ElliottBridge** [comment] 2022-05-07 12:05
> This is most likely caused by some error in the plotting part of the GUI. I'm guessing it's something with the x-scale display rather than the data. I'm working on this part right now, will check this too!

Any ideas about the phase stuff? I think it's either showing up wrong or convolving wrong. It's meant to be linear for that region all the way down to -inf noise floor, so it's not even that it's showing inaudible phase, it's that there shouldn't be any phase change at all. Perhaps it's linked with the x-axis issue? Just want these little graphing details fixed before I do a video on it, hope that makes sense, it's quite crucial since it's the only visual element you see. Thank you 🙂👍

**Comment by HEnquist** [comment] 2022-05-07 21:16
Can you try the new camilladsp v1.0.0, with the prerelease of the gui?
https://github.com/HEnquist/camillagui-backend/releases/tag/v1.0.0-rc2

The new version will plot the phase of FIR filters differently, but one can argue that the old version you show above is more correct. Linear phase means the phase changes linearly with frequency. It's not constant phase! A FIR filter gives a delay that is equal for all frequencies, and this delay means the phase wraps around quickly. That's what gives the messy phase plot.
The new version tries to find the peak of the impulse response to remove the delay, and this then gives a constant phase.

**Comment by HEnquist** [comment] 2022-05-26 11:52
Did it work properly in the new GUI? I'm closing this issue, if there are more problems please open a new issue in the camillagui repo :)

**Closed by HEnquist** 2022-05-26 11:52 UTC

**Comment by ElliottBridge** [comment] 2022-05-26 12:04
> Did it work properly in the new GUI? I'm closing this issue, if there are more problems please open a new issue in the camillagui repo :)

It did, thank you. There were a couple of little issues after this one, I've listed them on camillagui already.
