### ISSUE TITLE
Buffer underruns on macOS

### ISSUE THREAD

**Issue by herrernst** [HEnquist/camilladsp#173] opened 2022-01-11 17:03 UTC
Hi,

first of all thank you for your software, it's really great! I am using it on macOS Monterey for a 2.1 system to split out an additional low-passed, delay-adjusted and equalized subwoofer signal from a Blackhole input.

Unfortunately, I sometimes get buffer underruns, like every minute or so (but at random intervals), mostly when system load is higher than idle (like when I just start a new application).

I have tried increasing `chunksize` to 8192, tried different sample rates (44100 and 88200, because I mostly listen to 44,1kHz music; what is preferable?) for all elements in path (Blackhole, CamillaDSP, sound device). Also switched between Blackhole 2ch and 16ch.

Any more ideas, what I could do? I am using current next100 branch (CamillaDSP 1.0.0-alpha5), but I also have similar problems with 0.6.3.

Thanks!
Best regards, Ernst

```
2022-01-11 15:40:11.695980 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:40:11.702159 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-11 15:42:26.188789 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:42:26.194973 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-11 15:44:33.529896 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:44:33.536140 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-11 15:47:07.062226 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:47:07.068397 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-11 15:48:58.799811 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:48:58.823379 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-11 15:55:06.989857 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-11 15:55:07.002336 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
````

**Comment by HEnquist** [comment] 2022-01-11 20:27
Can you show the devices section of you config?

I'm guessing it's caused by a mismatch between the samplerates of blackhole and the dac. Currently blackhole doesn't allow changing the virtual samplerate the way an Alsaloop back device does. This means you need to use the asynchronous resampler to keep them in sync. Enable resampling and rate adjust, and set the resampler type to BalancedAsync.

**Comment by herrernst** [comment] 2022-01-11 21:27
I've set all devices to the same rate, also Blackhole.

![Screen Shot 2022-01-11 at 22 25 50](https://user-images.githubusercontent.com/20795/149024144-1b7fe15c-8d37-4023-befb-32f70e0416de.png)

Will try enabling resampling, but doesn't it introduce quality loss?

**Comment by HEnquist** [comment] 2022-01-11 21:52
They are using independant clock sources, so they will still be a little different. Since you get underruns, on your system Blackhole runs at a slightly lower rate than the dac, something on the order of 88190 vs 88200 Hz. This means the dac runs out of samples sometimes.
A future version of Blackhole will support locking the virtual samplerate to a real device, that will make the problem go away.
 
The quality loss from the resampling is very small. You can try AccurateAsync if you are worried about it, but already with BalancedAsync it should be far below audible.

**Comment by Wang-Yue** [comment] 2022-01-12 02:25
the BlackHole with clock sync is not available right now, and by the time it's available it will be a Pro feature.
you can hack the code and change the clock to be a little bit faster (change the multiplication factor of theHostClockFrequency, currently 1000000000.0, to something larger).
This in theory should solve your issue with no need to do SRC.

**Comment by herrernst** [comment] 2022-01-12 22:17
Thank you both for your suggestions.

Resampling works fine.

Adjusting the clock of BlackHole also worked. But I had to decrease the factor to something like 999950000.0 which has worked fine for some hours now. Any downsides to this? If I decrease it much more, I get dropouts and CamillaDSP prints "Samples were dropped, missing 1 buffers" because of overflowing buffers, I guess.

**Comment by HEnquist** [comment] 2022-01-12 22:24
Great that it's solved! If you speed up Blackhole too much then you will start to notice a slowly increasing delay, since the dac isn't consuming the samples as fast as Blackhole provides them. The delay will grow to the point where the Camillladsp buffers are full and you get the "samples were dropped" warning.

**Comment by herrernst** [comment] 2022-01-17 18:51
Sorry for reopening this again. I did not find a frequency for BlackHole which worked without underruns and overflows at the same time. 

So I am using ASRC now. Unfortunately, on high CPU load I still get dropouts:
````
2022-01-17 18:38:10.030040 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:38:10.041653 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:38:12.456392 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:38:12.479641 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:38:12.688586 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:38:12.711856 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:40:39.525116 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:40:39.536747 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:41:04.102317 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:41:04.113946 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:41:43.353907 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:41:43.504862 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:41:43.806681 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:41:43.872154 WARN [src/coreaudiodevice.rs:718] Samples were dropped, missing 15 buffers
2022-01-17 18:41:43.876356 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-17 18:41:44.201624 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-17 18:41:44.427091 WARN [src/coreaudiodevice.rs:718] Samples were dropped, missing 21 buffers
2022-01-17 18:41:44.445228 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
````
(underruns and overruns at the same time, no?)

config is:
```
  samplerate: 44100
  chunksize: 1024
  enable_resampling: true
  resampler_type: BalancedAsync
  enable_rate_adjust: true
```
Any ideas what I could do? In the long term I would like to run CamillaDSP as service (LaunchAgent?). Any tipps/best practice how this can be accomplished? Thanks again

**Comment by HEnquist** [comment] 2022-01-17 22:11
I'll try to reproduce this. Can you give an example of something that generates a suitable high CPU usage? What model is the mac you are running on?

I don't know anything about LaunchAgent unfortunately.

**Comment by herrernst** [comment] 2022-01-17 22:28
I just need to lauch some applications from the dock, like clicking Word, Excel and Powerpoint in quick succession. Or building a project in Xcode. Or executing `npm install` in a web project. Or possibly building camilladsp with cargo ;-)

I am using a Mac Mini 2018 which IMHO is quite fast still.

**Comment by HEnquist** [comment] 2022-01-17 22:49
That is certainly much faster that the old MacBook I'm working on :)
Could you try to catch a log on trace level when it happens?

**Comment by HEnquist** [comment] 2022-01-18 07:15
I just tried a complete build of camilladsp while playing music with the same config you used. I didn't get any glitches, and this is on an old MacBook Pro (mid 2012). Are you running a debug build with `cargo run someconfig.yml`? Or a release build with `cargo run --release someconfig.yml`?

**Comment by herrernst** [comment] 2022-01-21 18:36
Sorry for the late answer. I'm running a release build. Here's a trace with one WARN: https://pastebin.com/UByzW10S

**Comment by herrernst** [comment] 2022-01-21 18:47
Here's another one I've provoked by quitting and restarting Firefox with a lot of tabs open: https://pastebin.com/AfzN3vax

(I also couldn't reproduce it by building a large Rust project in the background. It mostly happens when starting or quitting applications.)

**Comment by HEnquist** [comment] 2022-01-21 19:52
Alright, I'll try launching some applications then. While I play with that, could you try raising the Camillladsp process priority? https://discussions.apple.com/thread/1491812

**Comment by herrernst** [comment] 2022-01-21 19:57
Already tried it, no difference.

**Comment by HEnquist** [comment] 2022-01-24 21:59
Ok I can make underruns on my old MacBook if I set the target_level to 1024 or lower. With a chunksize of 4096 and a target_level of 2048 it gets much better, I have only managed to provoke a single one. Can you live with a target_level of 2048 or higher?
If I make a guess, I would say that it takes longer to allocate memory while a large app is starting. And camilladsp needs to allocate memory for the audio chunks it sends between its threads, as well as to fit the output of the resampler.

**Comment by siraaris** [comment] 2022-01-26 07:16
I've also experienced this on macOS (CamillaDSP RC1 but I also think on Alpha3 previously) on a MOTU Ultralite mk5 and RME ML-32 DA Pro. Both using the respective Loopback capability on the devices for Capture (not using BlackHole).

It might be (transient) load/capacity related, but that doesn't seem to be a traceable or noticeable cause.

The RME was running at 192k samplerate (for both capture and playback) and at 96k for the MOTU.

**Comment by HEnquist** [comment] 2022-01-26 07:32
@siraaris what chunksize did you use? And was that without resampling?

**Comment by Wang-Yue** [comment] 2022-01-26 08:11
@siraaris wait, can you clarify your setup? Do you see buffer under/overruns when you are using the same interface (using the same clock) for I and O?

**Comment by siraaris** [comment] 2022-01-26 08:32
Hi @HEnquist I have set chunksize to 4096, target_level to 2048, without resampling.
Config file for the RME is attached.

@Wang-Yue it's the same device, in/out.

Aris

[keystone-rme-cdsp-v6.txt](https://github.com/HEnquist/camilladsp/files/7940046/keystone-rme-cdsp-v6.txt)

**Comment by siraaris** [comment] 2022-01-26 10:14
[trace.txt](https://github.com/HEnquist/camilladsp/files/7940783/trace.txt)

Attaching the trace file.

**Comment by HEnquist** [comment] 2022-01-26 12:05
I see a few underruns very early after starting, and then a few minutes of trouble-free playback. Is that usually how it behaves?

Without resampling then camilladsp has no way of adjusting to keep the target_level. The only thing it can do is to delay the start of the playback until the right amount of data is available. This delay is actually missing in the coreaudio backend. That means it will get a few underruns early on, until the underruns have increased the delay to a sufficient amount where it's stable.
I'll add a start delay like it's done here: https://github.com/HEnquist/camilladsp/blob/next100/src/wasapidevice.rs#L272

**Comment by siraaris** [comment] 2022-01-26 13:14
Yes, the best behaviour is a few underruns at the start and then generally good playback.

Interestingly enough, 0.6.3 works fine (initial buffer overruns then stabilises), but with rc1 the buffer overruns persist after the initial period.

This is with resampling turned on in both cases.

**Comment by siraaris** [comment] 2022-01-26 13:39
And with 0.6.3 the GUI reports the buffer level around 2000 whereas with rc1 the buffer level is over 5000.

**Comment by siraaris** [comment] 2022-01-27 05:42
A quick note, I added a BNC cable to synchronise clocks between RME Digiface AVB and the M-32 DA Pro and the issue has been resolved for me.

**Comment by HEnquist** [comment] 2022-01-27 14:19
I found the cause! There will be a fix shortly.

**Comment by herrernst** [comment] 2022-01-27 21:59
Naive question: If it really happens on memory allocation, isn't it possible to allocate the necessary memory on start and reuse it afterwards?

Some more observations: 
• I get the same underruns with 0.6.3. 
• With chunksize 4096, target_level: 2048 it's better, I rarely get them
• I always get them when I quit iOS Simulator, even with above chunksize (but maybe iOS Simulator messes around with Core Audio)

Waiting to try your fix.

**Comment by HEnquist** [comment] 2022-01-27 22:03
It's not on memory allocation, it's a scheduling issue where the capture thread sleeps longer than requested when the system is under high load.
The fix is here: https://github.com/HEnquist/camilladsp/commit/453bf36b34ebe1090c085239fa17271b5df21d6f
I just want to test it a little more before I release a new rc.

**Comment by herrernst** [comment] 2022-01-28 17:17
I was curious and tested your fix, but I haven't noticed a difference unfortunately:
````
2022-01-28 16:05:36.099012 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:05:36.180361 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:09:30.391224 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:09:30.400232 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:11:32.775885 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:11:32.810742 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:12.879058 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:12.902295 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:12.925531 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:12.960319 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:12.983578 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:12.995183 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:13.064771 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:13.204138 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:13.204286 WARN [src/coreaudiodevice.rs:725] Samples were dropped, missing 7 buffers
2022-01-28 16:26:13.366760 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:13.413083 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:13.425639 WARN [src/coreaudiodevice.rs:725] Samples were dropped, missing 6 buffers
2022-01-28 16:26:13.598800 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:26:13.610524 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:26:13.615770 WARN [src/coreaudiodevice.rs:725] Samples were dropped, missing 3 buffers
2022-01-28 16:30:02.179637 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:30:02.191216 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
2022-01-28 16:40:28.689715 WARN [src/coreaudiodevice.rs:370] Playback interrupted, no data available
2022-01-28 16:40:28.882056 WARN [src/coreaudiodevice.rs:725] Samples were dropped, missing 5 buffers
2022-01-28 16:40:28.887124 INFO [src/coreaudiodevice.rs:359] Restarting playback after buffer underrun
````
While doing regular work in the meantime. This is with chunksize 1024, higher chunksize would probably be better. But chunksize 4096 (with 44.1k sampling rate) like you have proposed already causes an noticable delay when watching videos.

**Comment by HEnquist** [comment] 2022-01-28 21:48
That is quite strange, the fix is a definite improvement on my old mac. With chunksize 1024 I can kan keep repeatedly opening and closing apps like Firefox and Xcode and only get the occasional underrun. I also never get several underruns close together like you do (at 16:26:12 for example), only singles. 

The Delay filter is very light, it won't cause any trouble.

**Comment by HEnquist** [comment] 2022-01-29 20:57
I have been investigating some more. I can reduce the few underpins I get by increasing the camilladsp priority with `nice`, for example like `nice -20 ./target/release/camilladsp mac.yml`. 
The cause for the underruns seems to be that when there is high system load, there can be a delay between when the capture thread becomes ready to start processing new data, until it actually starts. The delay varies but it's usually less than 20 ms. But 20 ms can be quite a lot, when running a chunksize of 1024 at 44100 Hz each chunk is just 23 ms. Then already a single chunk that is 20 ms late can be enough to cause an underrun.
The scheduling of threads is handled by the operating system, apart from playing with priorities there isn't much that can be done to affect it. Can you try a chunk size of 2048? Maybe that's an acceptable compromise between latency and underrun risk.

**Comment by siraaris** [comment] 2022-01-30 06:12
@HEnquist is your last comment with your patch?

Just a thought but would GCD for Coreaudio be of any help (https://lib.rs/crates/dispatch). Assume it would fracture your x platform architecture. 

I tried setting chunksize to 2048 with rc1 instead of 4096 but that wasn't stable, continual choppy sound: I'll send the trace shortly.

**Comment by HEnquist** [comment] 2022-01-30 08:02
Yes with the latest patch! Did you try with or without it? 

I may be able to use GCD internally in the coreaudio backend, will try it. Thanks for the tip! Don't know if it will help but it's worth a try.

**Comment by Wang-Yue** [comment] 2022-01-30 16:23
My experience is gcd won’t improve CoreAudio performance. I tried but it only made things slower if used incorrectly.  The key idea to improve CoreAudio (or any async audio api) performance is really simple: don’t block thread, don’t use locks, don’t do work in the audio thread. Instead use lock free ring buffers based on atomic operations. The Cmus / MPD output code I wrote are good demonstrations (essentially the same), and has much better performance than say, VLC and many other software programs.

**Comment by siraaris** [comment] 2022-01-30 17:54
@HEnquist the latest patch is much better behaved for me. I can reduce the chunksize to 2048 and it's stable.

**Comment by HEnquist** [comment] 2022-01-30 22:28
@herrernst and @siraaris can you try the new `coreaudiotweak` branch? 
https://github.com/HEnquist/camilladsp/tree/coreaudiotweak
It includes various tweaks, including using a semaphore from GCD to wake up the capture thread after the callback has delivered more samples. It looks quite promising on my machine.

**Comment by siraaris** [comment] 2022-02-02 12:27
hi @HEnquist, I've been using the coreaudiotweak version for a few days, and its much more stable (less restarts). Thank you.

**Comment by HEnquist** [comment] 2022-02-02 13:07
Thanks for the feedback @siraaris !

@herrernst did you have a chance to try it too?

**Comment by herrernst** [comment] 2022-02-02 19:40
Thank you for your effort. Seems to be better, but not perfect though.

**Comment by HEnquist** [comment] 2022-02-02 19:53
> Thank you for your effort. Seems to be better, but not perfect though.

Can I have some more details please? The config and a trace-level log would be useful.

**Comment by herrernst** [comment] 2022-02-02 21:15
config: https://pastebin.com/5XLevwqU
log: https://zerobin.net/?31ced287a2460815#1pBbn0C1BW9lpGjfumsKEgaQeP+Qkot3GXEVVTqxAso=

relevant log sections:
````
     Running `target/release/camilladsp -vv /Users/user/Documents/audio/camilla-xover-ni6.yml`
2022-02-02 20:53:16.790896 INFO [src/bin.rs:711] CamillaDSP version 1.0.0-rc1
2022-02-02 20:53:16.790926 INFO [src/bin.rs:712] Running on macos, x86_64
2022-02-02 20:53:16.924292 WARN [src/coreaudiodevice.rs:375] Playback interrupted, no data available
2022-02-02 20:53:16.935797 INFO [src/coreaudiodevice.rs:364] Restarting playback after buffer underrun
2022-02-02 20:53:36.346557 WARN [src/coreaudiodevice.rs:375] Playback interrupted, no data available
2022-02-02 20:53:36.358214 INFO [src/coreaudiodevice.rs:364] Restarting playback after buffer underrun
2022-02-02 20:53:54.886644 WARN [src/coreaudiodevice.rs:375] Playback interrupted, no data available
2022-02-02 20:53:54.921491 INFO [src/coreaudiodevice.rs:364] Restarting playback after buffer underrun
````
first underrun is on start (ok), then i randomly click to open some apps in Dock (in this case 6 in total, Mail, Firefox, Chrome, Word, Excel, Maps).

**Comment by Wang-Yue** [comment] 2022-02-03 04:10
In your Audio thread, are you (or underlying calls) using 1) locks/mutex/semaphores 2) doing system calls such as memory allocation?  If either one is a yes, you can simply remove them and use a high performance lock free ring buffer instead.

**Comment by HEnquist** [comment] 2022-02-03 13:31
@Wang-Yue that depends on which thread you mean, there are three threads that handle the audio. The capture callback function is pushing data to a channel, https://docs.rs/crossbeam-channel/latest/crossbeam_channel/
The capture thread sleeps waiting for the small audio packets on the receiving end of that channel. When it receives a packet, it adds the data to a buffer and if it has enough data to build a chunk, it optionally resamples, and sends off an audio chunk in a channel leading to the processing thread. Then the processing thread passes it on to the playback thread in yet another channel. The capture thread allocates memory for the audio chunks it sends. I have tracked how long the allocations take, and they have never been responsible for the underruns in my system. The trouble is something else, that the sleeping threads are slow to start when the system is under heavy load. On an idle system it's nearly instant, but when there is high load it starts varying a lot and I often see delays of 10-20ms. Using the GCD semaphore to wake up the capture thread gives a small but useful improvement of a few milliseconds, but the issue us still there. I guess this is a limitation of running the DSP in user space, where it has to share resources with all the other apps.
With chunksize and target_level set to 1024 at 44100Hz there is only 23 ms of margin before the playback is starved. This just seems too little on a system that is used heavily in parallel with the audio processing.

**Comment by siraaris** [comment] 2022-02-03 13:55
@HEnquist what constitutes high load? I'm only running an AVB controller and Camilla on a Mac M1 mini with no other apps. I guess there may be crons on the OS that spike the CPU from time to time?

**Comment by HEnquist** [comment] 2022-02-03 15:35
@siraaris That's a good question. Things like compiling camilladsp works fine, even if all CPU cores are at 100%. But the startup phase of large apps seems to give the "right" type of load to cause issues.

**Comment by HEnquist** [comment] 2022-05-02 19:54
1.0.0 released!

**Closed by HEnquist** 2022-05-02 19:54 UTC
Labels: macOS
