### ISSUE TITLE
EZBEQ cooperation issues After ezbeq uploads data, camilladsp is invalid

### ISSUE THREAD

**Issue by zorgzola** [HEnquist/camilladsp#354] opened 2024-08-25 07:56 UTC
I am using ezbeq  and currently encountering a problem:
 Ezbeq clicked upload,  The slot showed the movie name, but Camilla DSP WEBUI do not see the data. 
REW detects no change in frequency response.
CamillaDSP v2.0.3 ezbeq（windows）v2.1.0a11

I downloaded the logs of camilladsp before and after ezbeq upload and clean. Please help me
![camiladsp log](https://github.com/user-attachments/assets/5a4e66f1-73a7-4645-8c45-18347bd596fd)
[camiladsp.log.txt](https://github.com/user-attachments/files/16739411/camiladsp.log.txt)

**Comment by HEnquist** [comment] 2024-08-25 09:53
Do I understand correctly that adding the filters works ok, but removing them does not?

**Comment by zorgzola** [comment] 2024-08-25 10:05
Please apologize for my English.
I mean adding the filters, The log shows OK, but it actually didn't take effect. I observed the camilladsp webui and didn't find any filters (I clicked Fetch from DSP'), And I tested the sub with Rew software, but the filters did not load.

**Comment by zorgzola** [comment] 2024-08-25 10:57
I installed Cammilladsp and EZBEQ on three computers, one Mac and two Windows.
They all have the same issues

**Comment by HEnquist** [comment] 2024-08-25 19:54
I don't see anything obviously wrong in the logs, but it's been cut and it would help to see more. Can you try again, and include everything? It's ok if it gets very long. Also please note at what times you expect something to happen, and what that should be.

**Comment by zorgzola** [comment] 2024-08-26 02:58
Thanks for your work.
I tested it on a mac today, and here is the log of the ezbeq interaction.
I thought that when ezbeq uploaded the filters, the "Filtes" and "Pipeline" in the CamillaDSP WEBUI would see the data (when I clicked "Fetch from DSP"), but in fact it does not show anything, am I wrong?
[camilladsp.log](https://github.com/user-attachments/files/16743453/camilladsp.log)

![CamillaDSP](https://github.com/user-attachments/assets/959a8461-8596-40c4-bfc3-3b46c542e28d)

**Comment by zorgzola** [comment] 2024-08-26 08:55
and after uploading Filters on ezbeq, use REW Generator to send the frequency of BEQ maximum boost. The volume input and output levels in CamillaDSP WEBUI are the same.
However, the output level of manually adding Filters (Peaking Gain+) is different.
![camiladsp ezbeq](https://github.com/user-attachments/assets/2c169669-bce8-4b21-8418-5de0dbb7725d)

**Comment by HEnquist** [comment] 2024-08-26 20:58
Thanks for the videos! That made things quit clear. The problem is that ezbeq sends a "Reload" command just after the SetConfig command. The SetConfig command is enough! The "Reload" command makes it apply the original config again. That's why you see the meter jump up for just a fraction of a second and then return to where it was.
Please open an issue in the ezbeq repo!

**Comment by zorgzola** [comment] 2024-08-27 00:37
Thanks again.

**Comment by HEnquist** [comment] 2024-08-27 08:53
Closing this since the problem is not in CamillaDSP.

**Closed by HEnquist** 2024-08-27 08:53 UTC
