### ISSUE TITLE
Unable to use aggregate device on Mac OS

### ISSUE THREAD

**Issue by geoshv** [HEnquist/camilladsp#301] opened 2023-08-19 17:55 UTC
Hyli, Henquist! I got camillaDSP working and upsampling the audio. The quality is amazing! Congratulations on your work!

The problem I'm having is when using an aggregate device(I want to upsample dolby atmos) CamillaDSP doesnt start. it gives me the following message:
bin.rs344 playback error: unknown property

running listdevices i get two different channel numbers: 8 on the default output stream config and 14 on all supported stream configs.

8 is my primary hdmi audio out and the aggregate is 8+6 from the second audio device(soundpusher)

Thanks in advance!
Geosh

**Comment by HEnquist** [comment] 2023-08-19 18:49
Hi Geosh! It would help a lot if you try starting with debug logging enabled (with -v). Then post the log output (all of it) and your config file here.

**Comment by HEnquist** [comment] 2023-10-13 21:33
Closing due to lack of activity.

**Comment by ChristiaanWillemsen** [comment] 2024-02-19 08:38
I can confirm that this is the case: Any CoreAudio Aggregate Device does not show up in the GUI list as well, and using the name will not make it work either. I don't see anything special in the log about this either. It's just as if the device does not exist.

**Comment by HEnquist** [comment] 2024-02-19 22:27
This will be fixed in the next release, see pr here: https://github.com/HEnquist/camilladsp/pull/327

**Comment by HEnquist** [comment] 2024-02-20 19:36
fixed in v2.0.3

**Closed by HEnquist** 2024-02-20 19:36 UTC
Labels: bug, macOS
